jobs:
  'Lint':
    docker: deltacidocker/node:12
    steps:
      - name: Install npm
        run: npm i
        when.changed: '**/package*.json' #
      - name: Build modules
        run: npm run build
      - name: Lint changed files #
        run: |
          # If not it's a commit, check the files changed in this commit
          git fetch origin $GITHUB_SHA --depth=2
          CHANGED_FILES=$( git diff-tree --no-commit-id --name-only --diff-filter ACMRTUXB -r $GITHUB_SHA )
          printf "\nThese files have changed in $GITHUB_SHA:\n$CHANGED_FILES\n"
          # Don't include files like LICENSE and css files
          CHANGED_JS_FILES=$(echo "$CHANGED_FILES" | sed -e '/^.\+\(mjs\|tsx\|jsx\|js\|ts\)$/!d')
          for FILE_NAME in $CHANGED_JS_FILES
          do
            npm run eslint -- $FILE_NAME
